In [1]:
import pandas as pd

test_df = pd.read_csv("../dataset/processed/updated_customer_shopping_behaviour_data.csv")

In [2]:
test_df

      customer_id  age  gender  ... frequency_of_purchases     age_group  purchase_frequency_days
0               1   55    Male  ...            Fortnightly   Middle_Aged                       14
1               2   19    Male  ...            Fortnightly   Young_Adult                       14
2               3   50    Male  ...                 Weekly   Middle_Aged                        7
3               4   21    Male  ...                 Weekly   Young_Adult                        7
4               5   45    Male  ...               Annually  Senior_Adult                      365
...           ...  ...     ...  ...                    ...           ...                      ...
3895         3896   40  Female  ...                 Weekly  Senior_Adult                        7
3896         3897   52  Female  ...              Bi-Weekly   Middle_Aged                       14
3897         3898   46  Female  ...              Quarterly   Middle_Aged                       90
3898         3899   44  Female  ...                 Weekly  Senior_Adult                        7
3899         3900   52  Female  ...              Quarterly   Middle_Aged                       90

[3900 rows x 19 columns]

In [3]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   object
 16  frequency_of_purchases   3900 non-null   object
 17  age_group                3900 non-null   object
 18  purchase_frequency_days  3900 non-null   int64
dtypes: float64(1), int64(5), object(13)
memory usage: 579.0+ KB

In [12]:
test_df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [5]:
test_df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating              0
subscription_status        0
shipping_type              0
discount_applied           0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
age_group                  0
purchase_frequency_days    0
dtype: int64

In [6]:
test_df.duplicated().sum()

np.int64(0)

In [8]:
# Find unique values of every columns along with their numbers and Datatype
for column in test_df.columns:
    print(f"Number of Unique Values of {column} is ",test_df[column].nunique(),
          f" And Datatype is ",test_df[column].dtype)
    print(f"\nUnique Values of {column} : \n",test_df[column].unique())
    print('*'*50)

Number of Unique Values of customer_id is  3900  And Datatype is  int64

Unique Values of customer_id :
 [   1    2    3 ... 3898 3899 3900]
**************************************************
Number of Unique Values of age is  53  And Datatype is  int64

Unique Values of age :
 [55 19 50 21 45 46 63 27 26 57 53 30 61 65 64 25 52 66 31 56 18 38 54 33
 36 35 29 70 69 67 20 39 42 68 49 59 47 40 41 48 22 24 44 37 58 32 62 51
 28 43 34 23 60]
**************************************************
Number of Unique Values of gender is  2  And Datatype is  object

Unique Values of gender :
 ['Male' 'Female']
**************************************************
Number of Unique Values of item_purchased is  25  And Datatype is  object

Unique Values of item_purchased :
 ['Blouse' 'Sweater' 'Jeans' 'Sandals' 'Sneakers' 'Shirt' 'Shorts' 'Coat'
 'Handbag' 'Shoes' 'Dress' 'Skirt' 'Sunglasses' 'Pants' 'Jacket' 'Hoodie'
 'Jewelry' 'T-shirt' 'Scarf' 'Hat' 'Socks' 'Backpack' 'Belt' 'Boots'
 'Gloves']
**************************************************
Number of Unique Values of category is  4  And Datatype is  object

Unique Values of category :
 ['Clothing' 'Footwear' 'Outerwear' 'Accessories']
**************************************************
Number of Unique Values of purchase_amount is  81  And Datatype is  int64

Unique Values of purchase_amount :
 [ 53  64  73  90  49  20  85  34  97  31  68  72  51  81  36  38  48  62
  37  88  22  25  56  94  79  67  91  33  69  45  60  76  39 100  21  43
  54  55  30  28  59  24  83  46  70  29  26  58  96  40  32  95  41  47
  99  87  92  98  89  35  75  65  86  84  77  27  23  74  80  42  61  82
  78  93  50  57  66  44  52  71  63]
**************************************************
Number of Unique Values of location is  50  And Datatype is  object

Unique Values of location :
 ['Kentucky' 'Maine' 'Massachusetts' 'Rhode Island' 'Oregon' 'Wyoming'
 'Montana' 'Louisiana' 'West Virginia' 'Missouri' 'Arkansas' 'Hawaii'
 'Delaware' 'New Hampshire' 'New York' 'Alabama' 'Mississippi'
 'North Carolina' 'California' 'Oklahoma' 'Florida' 'Texas' 'Nevada'
 'Kansas' 'Colorado' 'North Dakota' 'Illinois' 'Indiana' 'Arizona'
 'Alaska' 'Tennessee' 'Ohio' 'New Jersey' 'Maryland' 'Vermont'
 'New Mexico' 'South Carolina' 'Idaho' 'Pennsylvania' 'Connecticut' 'Utah'
 'Virginia' 'Georgia' 'Nebraska' 'Iowa' 'South Dakota' 'Minnesota'
 'Washington' 'Wisconsin' 'Michigan']
**************************************************
Number of Unique Values of size is  4  And Datatype is  object

Unique Values of size :
 ['L' 'S' 'M' 'XL']
**************************************************
Number of Unique Values of color is  25  And Datatype is  object

Unique Values of color :
 ['Gray' 'Maroon' 'Turquoise' 'White' 'Charcoal' 'Silver' 'Pink' 'Purple'
 'Olive' 'Gold' 'Violet' 'Teal' 'Lavender' 'Black' 'Green' 'Peach' 'Red'
 'Cyan' 'Brown' 'Beige' 'Orange' 'Indigo' 'Yellow' 'Magenta' 'Blue']
**************************************************
Number of Unique Values of season is  4  And Datatype is  object

Unique Values of season :
 ['Winter' 'Spring' 'Summer' 'Fall']
**************************************************
Number of Unique Values of review_rating is  26  And Datatype is  float64

Unique Values of review_rating :
 [3.1 3.5 2.7 2.9 3.2 2.6 4.8 4.1 4.9 4.5 4.7 2.8 4.6 3.3 4.4 3.6 5.  4.
 3.7 4.2 3.9 3.  3.8 3.4 4.3 2.5]
**************************************************
Number of Unique Values of subscription_status is  2  And Datatype is  object

Unique Values of subscription_status :
 ['Yes' 'No']
**************************************************
Number of Unique Values of shipping_type is  6  And Datatype is  object

Unique Values of shipping_type :
 ['Express' 'Free Shipping' 'Next Day Air' 'Standard' '2-Day Shipping'
 'Store Pickup']
**************************************************
Number of Unique Values of discount_applied is  2  And Datatype is  object

Unique Values of discount_applied :
 ['Yes' 'No']
**************************************************
Number of Unique Values of previous_purchases is  50  And Datatype is  int64

Unique Values of previous_purchases :
 [14  2 23 49 31 19  8  4 26 10 37 34 44 36 17 46 50 22 32 40 16 13  7 41
 45 38 48 18 15 25 39 35 29 21 43  3  5 24 42 47 28 20 33  1  9 12 27 11
 30  6]
**************************************************
Number of Unique Values of payment_method is  6  And Datatype is  object

Unique Values of payment_method :
 ['Venmo' 'Cash' 'Credit Card' 'PayPal' 'Bank Transfer' 'Debit Card']
**************************************************
Number of Unique Values of frequency_of_purchases is  7  And Datatype is  object

Unique Values of frequency_of_purchases :
 ['Fortnightly' 'Weekly' 'Annually' 'Quarterly' 'Bi-Weekly' 'Monthly'
 'Every 3 Months']
**************************************************
Number of Unique Values of age_group is  5  And Datatype is  object

Unique Values of age_group :
 ['Middle_Aged' 'Young_Adult' 'Senior_Adult' 'Senior' 'Adult']
**************************************************
Number of Unique Values of purchase_frequency_days is  5  And Datatype is  int64

Unique Values of purchase_frequency_days :
 [ 14   7 365  90  30]
**************************************************

In [10]:
test_df[['frequency_of_purchases','purchase_frequency_days']]

     frequency_of_purchases  purchase_frequency_days
0               Fortnightly                       14
1               Fortnightly                       14
2                    Weekly                        7
3                    Weekly                        7
4                  Annually                      365
...                     ...                      ...
3895                 Weekly                        7
3896              Bi-Weekly                       14
3897              Quarterly                       90
3898                 Weekly                        7
3899              Quarterly                       90

[3900 rows x 2 columns]

In [11]:
test_df[['age','age_group']]

      age     age_group
0      55   Middle_Aged
1      19   Young_Adult
2      50   Middle_Aged
3      21   Young_Adult
4      45  Senior_Adult
...   ...           ...
3895   40  Senior_Adult
3896   52   Middle_Aged
3897   46   Middle_Aged
3898   44  Senior_Adult
3899   52   Middle_Aged

[3900 rows x 2 columns]