# Import Libraries and Dataset

In [1]:
import pandas as pd

In [2]:
csb = pd.read_csv("dataset/shopping_behavior_updated.csv")

# Understanding Dataset

In [3]:
# A short Table View of DataFrame
display(csb.sample(10))
print("Dataframe's Shape : - ",csb.shape)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
2039,2040,35,Male,T-shirt,Clothing,51,Minnesota,M,Olive,Spring,3.1,No,Next Day Air,No,No,31,Debit Card,Bi-Weekly
1152,1153,62,Male,Handbag,Accessories,49,Connecticut,M,Gold,Fall,4.0,No,Standard,Yes,Yes,8,PayPal,Every 3 Months
3310,3311,45,Female,Jacket,Outerwear,27,Iowa,M,Pink,Winter,3.6,No,Free Shipping,No,No,12,PayPal,Fortnightly
16,17,25,Male,Sunglasses,Accessories,36,Alabama,S,Gray,Spring,4.1,Yes,Next Day Air,Yes,Yes,44,Debit Card,Bi-Weekly
2392,2393,40,Male,Jeans,Clothing,62,Missouri,L,Silver,Spring,2.6,No,2-Day Shipping,No,No,36,Cash,Annually
2735,2736,46,Female,Skirt,Clothing,29,California,M,Yellow,Spring,3.0,No,Express,No,No,2,PayPal,Bi-Weekly
2212,2213,59,Male,Pants,Clothing,77,Nebraska,M,Brown,Winter,3.3,No,Next Day Air,No,No,22,Bank Transfer,Quarterly
3462,3463,44,Female,Jeans,Clothing,73,Michigan,L,Olive,Spring,4.5,No,Standard,No,No,34,Credit Card,Every 3 Months
3314,3315,55,Female,Socks,Clothing,94,Kansas,M,Violet,Spring,3.3,No,Standard,No,No,8,Credit Card,Quarterly
3029,3030,64,Female,Dress,Clothing,82,Georgia,M,Gold,Summer,3.1,No,Free Shipping,No,No,1,Debit Card,Quarterly

Dataframe's Shape : -  (3900, 18)

In [4]:
print("\nOverall Information of this Dataframe :: \n")
print(csb.info())

Overall Information of this Dataframe ::

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB
None

In [5]:
# Find unique values of every columns along with their numbers
for column in csb.columns:
    print(f"Number of Unique Values of {column} is ",csb[column].nunique(),
          f" And Datatype is ",csb[column].dtype)
    print(f"Unique Values of {column}\n",csb[column].unique())
    print('*'*50)

Number of Unique Values of Customer ID is  3900  And Datatype is  int64
Unique Values of Customer ID
 [   1    2    3 ... 3898 3899 3900]
**************************************************
Number of Unique Values of Age is  53  And Datatype is  int64
Unique Values of Age
 [55 19 50 21 45 46 63 27 26 57 53 30 61 65 64 25 52 66 31 56 18 38 54 33
 36 35 29 70 69 67 20 39 42 68 49 59 47 40 41 48 22 24 44 37 58 32 62 51
 28 43 34 23 60]
**************************************************
Number of Unique Values of Gender is  2  And Datatype is  object
Unique Values of Gender
 ['Male' 'Female']
**************************************************
Number of Unique Values of Item Purchased is  25  And Datatype is  object
Unique Values of Item Purchased
 ['Blouse' 'Sweater' 'Jeans' 'Sandals' 'Sneakers' 'Shirt' 'Shorts' 'Coat'
 'Handbag' 'Shoes' 'Dress' 'Skirt' 'Sunglasses' 'Pants' 'Jacket' 'Hoodie'
 'Jewelry' 'T-shirt' 'Scarf' 'Hat' 'Socks' 'Backpack' 'Belt' 'Boots'
 'Gloves']
**************************************************
Number of Unique Values of Category is  4  And Datatype is  object
Unique Values of Category
 ['Clothing' 'Footwear' 'Outerwear' 'Accessories']
**************************************************
Number of Unique Values of Purchase Amount (USD) is  81  And Datatype is  int64
Unique Values of Purchase Amount (USD)
 [ 53  64  73  90  49  20  85  34  97  31  68  72  51  81  36  38  48  62
  37  88  22  25  56  94  79  67  91  33  69  45  60  76  39 100  21  43
  54  55  30  28  59  24  83  46  70  29  26  58  96  40  32  95  41  47
  99  87  92  98  89  35  75  65  86  84  77  27  23  74  80  42  61  82
  78  93  50  57  66  44  52  71  63]
**************************************************
Number of Unique Values of Location is  50  And Datatype is  object
Unique Values of Location
 ['Kentucky' 'Maine' 'Massachusetts' 'Rhode Island' 'Oregon' 'Wyoming'
 'Montana' 'Louisiana' 'West Virginia' 'Missouri' 'Arkansas' 'Hawaii'
 'Delaware' 'New Hampshire' 'New York' 'Alabama' 'Mississippi'
 'North Carolina' 'California' 'Oklahoma' 'Florida' 'Texas' 'Nevada'
 'Kansas' 'Colorado' 'North Dakota' 'Illinois' 'Indiana' 'Arizona'
 'Alaska' 'Tennessee' 'Ohio' 'New Jersey' 'Maryland' 'Vermont'
 'New Mexico' 'South Carolina' 'Idaho' 'Pennsylvania' 'Connecticut' 'Utah'
 'Virginia' 'Georgia' 'Nebraska' 'Iowa' 'South Dakota' 'Minnesota'
 'Washington' 'Wisconsin' 'Michigan']
**************************************************
Number of Unique Values of Size is  4  And Datatype is  object
Unique Values of Size
 ['L' 'S' 'M' 'XL']
**************************************************
Number of Unique Values of Color is  25  And Datatype is  object
Unique Values of Color
 ['Gray' 'Maroon' 'Turquoise' 'White' 'Charcoal' 'Silver' 'Pink' 'Purple'
 'Olive' 'Gold' 'Violet' 'Teal' 'Lavender' 'Black' 'Green' 'Peach' 'Red'
 'Cyan' 'Brown' 'Beige' 'Orange' 'Indigo' 'Yellow' 'Magenta' 'Blue']
**************************************************
Number of Unique Values of Season is  4  And Datatype is  object
Unique Values of Season
 ['Winter' 'Spring' 'Summer' 'Fall']
**************************************************
Number of Unique Values of Review Rating is  26  And Datatype is  float64
Unique Values of Review Rating
 [3.1 3.5 2.7 2.9 3.2 2.6 4.8 4.1 4.9 4.5 4.7 2.8 4.6 3.3 4.4 3.6 5.  4.
 3.7 4.2 3.9 3.  3.8 3.4 4.3 2.5]
**************************************************
Number of Unique Values of Subscription Status is  2  And Datatype is  object
Unique Values of Subscription Status
 ['Yes' 'No']
**************************************************
Number of Unique Values of Shipping Type is  6  And Datatype is  object
Unique Values of Shipping Type
 ['Express' 'Free Shipping' 'Next Day Air' 'Standard' '2-Day Shipping'
 'Store Pickup']
**************************************************
Number of Unique Values of Discount Applied is  2  And Datatype is  object
Unique Values of Discount Applied
 ['Yes' 'No']
**************************************************
Number of Unique Values of Promo Code Used is  2  And Datatype is  object
Unique Values of Promo Code Used
 ['Yes' 'No']
**************************************************
Number of Unique Values of Previous Purchases is  50  And Datatype is  int64
Unique Values of Previous Purchases
 [14  2 23 49 31 19  8  4 26 10 37 34 44 36 17 46 50 22 32 40 16 13  7 41
 45 38 48 18 15 25 39 35 29 21 43  3  5 24 42 47 28 20 33  1  9 12 27 11
 30  6]
**************************************************
Number of Unique Values of Payment Method is  6  And Datatype is  object
Unique Values of Payment Method
 ['Venmo' 'Cash' 'Credit Card' 'PayPal' 'Bank Transfer' 'Debit Card']
**************************************************
Number of Unique Values of Frequency of Purchases is  7  And Datatype is  object
Unique Values of Frequency of Purchases
 ['Fortnightly' 'Weekly' 'Annually' 'Quarterly' 'Bi-Weekly' 'Monthly'
 'Every 3 Months']
**************************************************

Some columns need changes of thier data type, i.e.
 * Customer ID : int64 -> int16
 * Age: int64 -> int8
 * Gender : object -> Category
 * Category : object -> Category
 * Size : object -> Category
 * Season : object -> Category
 * Subscription Status :object -> Category
 * Discount Applied : object -> Category
 * Payment Method : object -> Category
 * Frequency of Purchases : object -> Category

These columns contain less than 10 type category.
it's help to decrease memory usage, Faster operation in many cases. .

In [6]:
display("Statistical Information About Numeric Columns",csb.describe(exclude = 'object'))
print('\n')
display("Statistical Information About Object Columns",csb.describe(include = 'object'))

'Statistical Information About Numeric Columns'

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

'Statistical Information About Object Columns'

,Gender,Item Purchased,Category,Location,Size,Color,Season,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Payment Method,Frequency of Purchases
count,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900
unique,2,25,4,50,4,25,4,2,6,2,2,6,7
top,Male,Blouse,Clothing,Montana,M,Olive,Spring,No,Free Shipping,No,No,PayPal,Every 3 Months
freq,2652,171,1737,96,1755,177,999,2847,675,2223,2223,677,584

In [7]:
# Check Presence of Null Vlues
csb.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
print(csb.duplicated().sum())

0

# Data Dleaning

In [9]:
df = csb.copy()

In [10]:
# Clean and normalize column names
df.columns = df.columns.str.lower().str.replace(' ','_')
df = df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [11]:
df = df.astype({'customer_id':'int16','age':'int8','gender':'category','category':'category',
    'size':'category','season':'category','subscription_status':'category','shipping_type':'category',
         'discount_applied':'category','payment_method':'category','frequency_of_purchases':'category'})

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int16
 1   age                     3900 non-null   int8
 2   gender                  3900 non-null   category
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   category
 5   purchase_amount         3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   category
 8   color                   3900 non-null   object
 9   season                  3900 non-null   category
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   category
 12  shipping_type           3900 non-null   category
 13  discount_applied        3900 non-null   category
 14  promo_code_used         3900 non-null   object
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   category
 17  frequency_of_purchases  3900 non-null   category
dtypes: category(9), float64(1), int16(1), int64(2), int8(1), object(4)
memory usage: 260.9+ KB

**merory usage decrease from 548.6+ KB to 260.9+ KB**

# Feature Engineering

In [13]:
def grouping_age(age):
    """Categorize age values into human-readable segments."""
    if 18 <= age <= 25:
        return 'Young_Adult'
    elif 26 <= age <= 35:
        return 'Adult'
    elif 36 <= age <= 45:
        return 'Senior_Adult'
    elif 46 <= age <= 60:
        return 'Middle_Aged'
    elif age > 60:
        return 'Senior'
    else:
        return 'Teenager'

df['age_group'] = df['age'].apply(grouping_age)
df[['age','age_group']]

      age     age_group
0      55   Middle_Aged
1      19   Young_Adult
2      50   Middle_Aged
3      21   Young_Adult
4      45  Senior_Adult
...   ...           ...
3895   40  Senior_Adult
3896   52   Middle_Aged
3897   46   Middle_Aged
3898   44  Senior_Adult
3899   52   Middle_Aged

[3900 rows x 2 columns]

In [14]:
df['frequency_of_purchases'].value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [15]:
frequency_mapping = {
            'Fortnightly': 14,
            'Weekly': 7,
            'Monthly': 30,
            'Quarterly': 90,
            'Bi-Weekly': 14,
            'Annually': 365,
            'Every 3 Months': 90
        }
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [16]:
df[['frequency_of_purchases','purchase_frequency_days']]

     frequency_of_purchases  purchase_frequency_days
0               Fortnightly                       14
1               Fortnightly                       14
2                    Weekly                        7
3                    Weekly                        7
4                  Annually                      365
...                     ...                      ...
3895                 Weekly                        7
3896              Bi-Weekly                       14
3897              Quarterly                       90
3898                 Weekly                        7
3899              Quarterly                       90

[3900 rows x 2 columns]

In [17]:
(df['promo_code_used'] == df['discount_applied']).sum()

np.int64(3900)

In [18]:
# Drop 'promo_code_used' column because it's value is similar with 'discount_applied', Thus it's create redundency
df.drop('promo_code_used',axis=1,inplace=True)

In [19]:
df

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle_Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young_Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle_Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young_Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Senior_Adult,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Senior_Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle_Aged,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle_Aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Senior_Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle_Aged,90

In [24]:
# Upload new Updated DataFrame into csv fFileExistsError
df.to_csv('dataset/updated_customer_shopping_behaviour_data.csv',index = False)